### PR TITLE
Tiny bug fixes and adding tests to improve code coverage

### PR DESCRIPTION
**Pull request by bjarnemagnussen**
### Reasoning

The segwit and multisig functionalities have not received proper tests and the code coverage was a little bit ignored. This PR tries to fix that. It fixes a few small bugs (5ced69d, 5834f61, 13ac76b and 
4020f93) and adds many tests to improve the code coverage.

All tests should pass by Travis if it weren't for the fact that right now `SmartbitAPI` is offline.

New constants `VERSION_2` and `OP_CHECKMULTISIG` are added to `bit/constants.py` **without** being used by any commit and may seem unnecessary. However, those will be used for PSBT implementation in future PRs.

That's all!

### CODE REVIEW

**Comment by bjarnemagnussen** [comment]
Thanks @ofek! :)

**Comment by bjarnemagnussen** [comment]
I just added two tiny commits and now that the SmartbitAPI is online again the tests should pass. 

However, regarding code coverage: Does anyone know why e.g. [this](https://codecov.io/gh/ofek/bit/src/wip-general-improvements/bit/wallet.py#L239) line is yellow?

**Comment by teran-mckinney** [comment]
> I just added two tiny commits and now that the SmartbitAPI is online again the tests should pass.
> 
> However, regarding code coverage: Does anyone know why e.g. [this](https://codecov.io/gh/ofek/bit/src/wip-general-improvements/bit/wallet.py#L239) line is yellow?

Not sure, unfortunately.

**Comment by teran-mckinney** [comment]
Sorry for the wait on this! Since @ofek already looked at it and you're submitting it, I'll go ahead and merge it. Looks great to me. Thank you!

**Pull request merged**
