### PR TITLE
grow to 0.6.2

### PR DESCRIPTION
**Pull request by bjarnemagnussen**
We should probably make a new release. 

@ofek Can you check why the docs online are not being updated, see e.g. Network on the [online](https://ofek.dev/bit/guide/network.html) vs "[offline](https://github.com/ofek/bit/blob/master/docs/source/guide/network.rst)" version.

### CODE REVIEW

**Comment by bjarnemagnussen** [comment]
BTW:
Screenshot from 2020-07-03 13-19-35
Yay!

**Comment by ofek** [comment]
https://travis-ci.org/github/ofek/bit/jobs/704623989#L517

**Comment by bjarnemagnussen** [comment]
> https://travis-ci.org/github/ofek/bit/jobs/704623989#L517

Oh, I will take a look at it before merging this PR

**Comment by ofek** [comment]
& rebase after https://github.com/ofek/bit/pull/116

**Comment by bjarnemagnussen** [comment]
I am not sure if this fixes the documentation, as I had problems to get the sphinx setup correctly on my machine. @ofek Maybe you can check it locally before merging?

**Pull request merged**
