### PR TITLE
API fixes

### PR DESCRIPTION
**Pull request by bjarnemagnussen**
**In continuation of #86**

* Removes Bitpay API
* Adds three new APIs
* Adds new test address with many unspents and guaranteed > 0 balance
* Increases timeout for network testing

### CODE REVIEW

**Comment by bjarnemagnussen** [comment]
Well, I was considering removing `BTCcomAPI`, because it needs a _fake user agent_ to work and can return messages regarding _abusive use_ of their API... In the end I added a check for that and have added `BTCcomAPI` very low in the lists of `NetworkAPI`.

**Comment by bjarnemagnussen** [comment]
Sorry for the mess... But it is very hard to get testing of the APIs correct with the numerous ways errors can happen. 

But I think now it works and is ready to be reviewed. I didn't experience issues with BTCcom locally, only after pushing the code and using Travis for some reason.

**Comment by bjarnemagnussen** [comment]
Ah right, I will look into updating docs

**Comment by bjarnemagnussen** [comment]
Just some quick updates to the docs I finally came around to make.

But now it seems that `BTCcomAPI` is making troubles, and I will have to look into that and eventually remove it again as it is just too much work to maintain this API.

**Comment by ofek** [comment]
Merge now or wait?

**Comment by bjarnemagnussen** [comment]
Wait some more as I will find the time later this week to checkout what is happening. :)

**Comment by bjarnemagnussen** [comment]
I have force push the branch with the new commits. The reason was that I have decided to drop `BTCcomAPI`, as that one does not seem to be interested in use without an API key and bans IPs quickly.

I have also made minor changes to both `BlockstreamAPI` and `BlockchainAPI`, as it became clear to me that Blockstream is giving errors to some addresses with _many_ transactions and only supports 50 _unconfirmed_ transactions. Blockchain does only support up to 1000 UTXOs. In all those cases the API will now raise a `ExcessiveAddress` exception, which is also described in the docs. I believe this behaviour is better than potentially ending up in inconsistent behaviour. And to use addresses with such history it is advised to use an own node.

**Comment by bjarnemagnussen** [comment]
@teran-mckinney Do you have the possibility to review this in the near future?

**Comment by teran-mckinney** [comment]
Ok! Hopefully will remember to do this today. If not, please ping me again.

Sorry for the wait.

**Comment by teran-mckinney** [comment]
Nice job! :)

**Pull request merged**
