### PR TITLE
added custom url path functionality

### PR DESCRIPTION
**Pull request by chikko80**
Added an optional path variable --> enables connection to a node on a route other than "/"

### CODE REVIEW

**Review by ofek — APPROVED** [review]
Thanks!

**Comment by chikko80** [comment]
No problem :) could you also update the official pip package? I need the updated version in my current project and it would be pretty handy if I could install the package via pip because of my docker architecture

**Comment by ofek** [comment]
Sure, I'll do it this weekend!

**Comment by ofek** [comment]
https://pypi.org/project/bit/0.8.0/

**Pull request merged**
