### PR TITLE
Adjusts transaction size calculation

### PR DESCRIPTION
**Pull request by bjarnemagnussen**
A simple fix to the slightly off transaction size calculation, as mentioned in #106

### CODE REVIEW

**Comment by deliugard** [comment]
Please take out the Unspects and Outputs bytes calculation function separately.
This will add the ability to pre-calculate the exact fee and check for the availability of these funds in the wallet.

**Comment by deliugard** [comment]
@bjarnemagnussen 
If the calculation focuses on virtual bytes (as you said here), then p2sh is also not correct.
You have registered vsize 292. However, the size of the next transaction is much smaller (only 206), although the IN address is p2sh:
https://blockstream.info/tx/94437469c7191710cf49279c90f3a24e3a29e6720d81819c37529afa3e312539
and the IN address - https://www.blockchain.com/btc/address/339CTt7VemsNcWdPCp3EGu8CrhLG8anQGK (P2SH)

**Comment by deliugard** [comment]
I also transferred your code for calculating the size of the transaction, maybe I was mistaken somewhere, but not with one type of wallet, the number of correct bytes did not match. In other matters, the error can be seen in the message above by manually checking

**Comment by bjarnemagnussen** [comment]
It would be better in the future if you actually provide the data and parameters you use for generation, e.g. what fee rate did you define and by how much did it vary?

As stated with a comment in the code the 292 bytes that you refer to are for P2SH-Multisig (Legacy == NOT Segwit), and is therefore not used for a segwit multisig input that was nested with P2SH (a.k.a NP2WSH input). The size for such an input will depend on the specific redeem script (e.g. if it is a 2-of-3 or 2-of-2, etc.). Currently it is simply hardcoded for 2-of-3, which is not optimal. Furthermore, it should be 140 (rounded up) and not 139 (fixed with a new commit). 

In your case however, as you are spending a 2-of-2 multisig the vsize of your input would only correspond to 131 vBytes, since it is missing exactly one public key in the redeem script (34 bytes = 34/4 vBytes = 8.5 vBytes).

As can be clearly seen inside `estimate_tx_fee` the calculation would then be:
`131 + 1 + 2*32 + 1 + 8 + 1 = 208`
The difference comes from the variable +/- 1 bytes in the signatures and rounding errors.

For the future a better way would clearly be to adjust the vsize depending on the Multisig type used and is something that should definitely be worked on. But that would be out of scope for this PR and should be added as its own PR.

You are very welcome to refactor `estimate_tx_fee` to have a function that calculates the size. I may do that in the future to better handle the transaction size for multisig, but unfortunately currently don't have the time.

**Comment by deliugard** [comment]
`
p2sh
outputs=[('39qc3brp49bbUrr9dYcpH2ahEnN2YBrXkR', 0.0009, 'btc')]
leftover='339CTt7VemsNcWdPCp3EGu8CrhLG8anQGK'
`
Getting 368 wbytes, but should be 206

**Comment by deliugard** [comment]
**p2pkh**
outputs: `[('36Jjm8it3saJHkiqtr7nxf1sERCS4Y47Cg', 0.01807614, 'btc')]`
leftover: `1MMzmUKEnaepxBdV2isKHjmNpfMeuuNCFv`
Getting **224** vbytes, but should be 223
https://blockstream.info/tx/85150a5476436eb7e8c70570a63d5c8068611daea1a18d5d3bad5f680cd241b6

**Comment by bjarnemagnussen** [comment]
> **p2sh**
> outputs: `[('39qc3brp49bbUrr9dYcpH2ahEnN2YBrXkR', 0.0009, 'btc')]`
> leftover: `339CTt7VemsNcWdPCp3EGu8CrhLG8anQGK`
> Getting **368** vbytes, but should be 206
> https://blockstream.info/tx/94437469c7191710cf49279c90f3a24e3a29e6720d81819c37529afa3e312539

How are you getting 368 vBytes? You set the fee rate to 1 and see what fee it calculates?

How did you "obtain" the unspent for this transaction? Is it correctly marked as a type `np2wsh`?

> p2pkh
> outputs: [('36Jjm8it3saJHkiqtr7nxf1sERCS4Y47Cg', 0.01807614, 'btc')]
> leftover: 1MMzmUKEnaepxBdV2isKHjmNpfMeuuNCFv
> Getting 224 vbytes, but should be 223
> https://blockstream.info/tx/85150a5476436eb7e8c70570a63d5c8068611daea1a18d5d3bad5f680cd241b6

It is as mentioned above impossible to know beforehand the exact the size. This is why this PR will use an upper estimate to make sure that setting the fee rate to 1 will not result in a fee rate too low to be broadcasted.

**Comment by deliugard** [comment]
@bjarnemagnussen 
I transferred the calculation function separately and just run the test.
Did I understand correctly that it is not possible to calculate the exact size of a transaction? Does the function return values ​​with a small error, but not lower than 1 satoshi per byte?

In general, in the future it is possible to calculate the exact number of bytes, or only an approximate?
ggwp

**Comment by bjarnemagnussen** [comment]
It is only possible to approximate the size.

The reason is that the signature can vary between 71 and 73 bytes (and could be even smaller but with exponentially smaller probability).

We should therefore use the larger estimate to make sure we don't slightly underpay fee.

Thinking about it to be very precise we should probably keep the "half" vBytes instead of immediately rounding them up in the imputs. Those would add up and should be rounded up as a last step in the `estimate_tx_fee` function. I will look into that and push those changes later.

**Comment by deliugard** [comment]
@bjarnemagnussen can the byte calculation function be taken out separately?
Of course I can do it myself, but since there are some improvements in this direction, it would be nice to have a common function for calculating the commission as well.
This is very useful if before making a transaction (otherwise there will be a standard node error if there is insufficient balance).

**Comment by bjarnemagnussen** [comment]
I just re-checked the sizes and for NP2WPKH (P2SH-Segwit) the calculation should be relatively precise as there are no "half" bytes unaccounted for. 

Regarding multisig we are currently slightly over-estimating (especially true if transaction contains multiple inputs). But I think it is be better to make changes to that in a separate PR with better size estimation using the redeem-script. This could also refactor `estimate_tx_fee` to allow direct estimation of sizes.

**Comment by bjarnemagnussen** [comment]
Ups, I just saw that we actually do account for the size of the redeem script in the `MultiSig` class. It's been two years, so I should have checked _before_ commenting. I am looking into what is wrong with the calculation.

**Comment by bjarnemagnussen** [comment]
Ok, the last push should fix the issues regarding size calcualtion for custom Multisigs. Refactoring should then happen in another PR.

I have added tests inside `test_wallet.py` to make sure calculations stay consistent. I will wait for the last changes to be approved.

**Comment by teran-mckinney** [comment]
@deliugard, what do you think about it?

**Comment by deliugard** [comment]
Excellent work. Thank you!

**Pull request merged**
