### PR TITLE
Added func for calculation transaction bytes num

### PR DESCRIPTION
**Pull request by deliugard**

### CODE REVIEW

**Comment by deliugard** [comment]
@ofek please check, wanna use it in projects.

**Comment by teran-mckinney** [comment]
I'm not sure I understand what "trx" means, a docstring might help. I think at a minimum this should have a test case.

**Comment by deliugard** [comment]
@teran-mckinney that is function for calculating the number of bytes (https://github.com/ofek/bit/issues/106#issuecomment-632606143)

**Comment by ofek** [comment]
Yes let's add a docstring and a test

**Comment by deliugard** [comment]
@ofek The function returns the number of bytes of the transaction, you can verify the result only manually, taking information from the finished transaction on any explorer.

In your library there is no way to get the sent transaction fee, or the number of bytes. Therefore, there is no way to implement a unit test.  
If this suits you i will add a docstring

**Comment by deliugard** [comment]
@ofek updated as required.

**Comment by teran-mckinney** [comment]
I don't see any tests.

**Comment by deliugard** [comment]
@teran-mckinney Please pay attention to the following message:

>The function returns the number of bytes of the transaction, you can verify the result only manually, taking information from the finished transaction on any explorer.
> 
> In your library there is no way to get the sent transaction fee, or the number of bytes. Therefore, there is no way to implement a unit test.
> If this suits you i will add a docstring

**Comment by ofek** [comment]
@deliugard You could mock, like here: https://github.com/ofek/bit/blob/master/tests/network/test_services.py

**Pull request closed without merging**
